import BackToInformation from "../BackToInformation";

const grading = [["A", "90 – 100", "4.0"], ["B", "80 – 89", "3.0"], ["C", "70 – 79", "2.0"], ["D", "60 – 69", "1.0"], ["F", "0 – 59", "0.0"]];
const courseTypes = [["Regular (College Prep)", "普通课程（大学预备）", "Designed to meet graduation requirements and prepare students for college and career.", "满足毕业要求，为大学和未来职业做好准备。"], ["Honors", "荣誉课程", "More challenging coursework with greater depth and pace.", "更具挑战性的课程，内容更深入、节奏更快。"], ["AP (Advanced Placement)", "大学先修课程", "College-level courses with the opportunity to earn college credit.", "大学水平课程，通过考试可获得大学学分。"]];
const requirements = [["English", "英语"], ["Mathematics", "数学"], ["Science", "科学"], ["Social Studies", "社会科学"], ["Health", "健康教育"], ["Physical Education", "体育"], ["World Language", "世界语言"], ["Electives", "选修课"]];
const notes = [["Stay Organized", "整理好作业、截止日期和考试日期。"], ["Ask for Help", "老师和辅导员都在这里帮助你。"], ["Plan Ahead", "你今天选择的课程会影响你的未来。"], ["Do Your Best", "努力与坚持会带来成功。"]];

export default function AcademicsPage() { return <main className="academics-page"><BackToInformation className="academics-page__back-button" /><div className="academics-page__container">
  <header className="academics-page__intro"><p>ACADEMIC GUIDE · 学术指南</p><h1>How School Academics Work <span>美国教育系统与学术指南</span></h1><small>Understanding how our academic system works will help you plan ahead and succeed with confidence.<br />了解学校的学术规则，能帮助你更好地规划未来，取得成功。</small></header>
  <section className="academics-section"><h2><b>1</b> Grades &amp; GPA <span>成绩与 GPA</span></h2><div className="academics-grid academics-grid--three"><article><h3>Grading Scale <span>评分标准</span></h3><div className="academics-grades">{grading.map(row => <div key={row[0]}><strong>{row[0]}</strong><span>{row[1]}</span><b>{row[2]}</b></div>)}</div><p className="academics-note">Grades are based on total points earned in each class.<br /><span>成绩基于每门课程获得的总分计算。</span></p></article><article><h3>Weighted GPA <span>加权 GPA</span></h3><p>Moanalua High School uses a weighted GPA. Honors, AP, and certain advanced courses receive extra quality points.</p><p>我校采用加权 GPA 计算方式，荣誉、AP 及部分进阶课程可获得额外分数。</p><div className="academics-table"><div><b>Course Level</b><b>Quality Points</b></div><div><span>Regular</span><span>1.0</span></div><div><span>Honors</span><span>1.5</span></div><div><span>AP / Advanced</span><span>2.0</span></div></div></article><article className="academics-illustrated"><h3>Class Rank <span>班级排名</span></h3><p>Class rank is based on weighted GPA and updated at the end of each semester.</p><p>班级排名基于加权 GPA，每学期末更新。</p><div className="academics-trophy" aria-hidden="true">★</div></article></div></section>
  <section className="academics-section"><h2><b>2</b> Where to Check Grades <span>在哪里查看成绩</span></h2><div className="academics-grid academics-grid--check"><article><h3>Jupiter Ed <span>成绩系统</span></h3><p>We use Jupiter Ed to manage grades, assignments, attendance, and more.</p><p>我们使用 Jupiter Ed 管理成绩、作业、出勤记录等信息。</p><a className="academics-link" href="https://login.jupitered.com/" target="_blank" rel="noreferrer">Open Jupiter Ed ↗</a></article><article><h3>How to Access <span>访问方式</span></h3><ol><li>Go to <b>jupitergrades.com</b></li><li>Enter your school email to log in.</li><li>View grades, assignments, attendance, and class feedback.</li></ol></article><aside><h3>Tip <span>小贴士</span></h3><strong>Check your grades regularly and don’t wait until the last minute!</strong><p>定期查看成绩，不要等到最后一刻。</p></aside></div></section>
  <section className="academics-section"><h2><b>3</b> Course Types <span>课程类型</span></h2><div className="academics-grid academics-grid--three">{courseTypes.map((item, index) => <article key={item[0]}><div className={`academics-course-icon academics-course-icon--${index + 1}`}>{index + 1}</div><h3>{item[0]} <span>{item[1]}</span></h3><p>{item[2]}</p><p>{item[3]}</p>{index > 0 && <small>+{index === 1 ? "0.5" : "1.0"} Quality Point</small>}</article>)}</div><div className="academics-example"><strong>Honors and AP courses are weighted. Regular courses are not.<span>荣誉课程和 AP 课程加权，普通课程不加分。</span></strong><p>Example 例子：AP A = 5.0 quality points · Regular A = 4.0 quality points</p></div></section>
  <section className="academics-section"><h2><b>4</b> Graduation Requirements <span>毕业要求（概览）</span></h2><p>Students must earn credits in the following areas. Requirements may change, so always check with your counselor.<br />学生需在以下领域获得学分才能毕业，具体要求可能会调整，请务必与辅导员确认。</p><div className="academics-requirements">{requirements.map(item => <article key={item[0]}><strong>{item[0]}</strong><span>{item[1]}</span></article>)}</div><p className="academics-note">Total credits required for graduation: refer to your counselor or course catalog.　毕业所需总学分：请参考课程手册或咨询辅导员。</p></section>
  <section className="academics-section"><h2><b>5</b> Important Notes <span>重要须知</span></h2><div className="academics-notes">{notes.map((item, index) => <article key={item[0]}><i>{index + 1}</i><strong>{item[0]}</strong><p>{item[1]}</p></article>)}</div></section>
  <footer className="academics-tip"><b>Tip 小贴士：</b><span>When in doubt, talk to your counselor!　有任何疑问，记得找你的辅导员聊一聊。</span></footer>
</div></main>; }
