"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Question = { id:string; title:string; zh:string; body:string; category:string; answers:number; time:string; badge:string; answered:boolean; mine?:boolean };
type Reply = { id:string; author:string; role:string; text:string; time:string; mine?:boolean };
type FeedMessage = { id:string; author:string; role:string; text:string; time:string; category:string; mine?:boolean; replyTo?:string };

const seed: Question[] = [
  {id:"graduate",title:"How do I know if I’m on track to graduate?",zh:"我怎么知道自己能否按时毕业？",body:"I’m still learning how credits and graduation requirements work. Who should I ask to review my progress?",category:"Classes & Grades",answers:3,time:"2h ago",badge:"Student Answer",answered:true},
  {id:"english",title:"How can I improve my English speaking?",zh:"我怎样提高英语口语？",body:"I understand more than I can say. What are some low-pressure ways to practice at school?",category:"English & Communication",answers:5,time:"5h ago",badge:"Peer Mentor",answered:true},
  {id:"clubs",title:"Where can I find clubs that match my interests?",zh:"我在哪里可以找到适合自己的社团？",body:"I’m new and don’t know anyone yet. Is there a club list or someone who can introduce me?",category:"School Life",answers:4,time:"Yesterday",badge:"Student Answer",answered:true},
  {id:"friends",title:"I feel shy and it’s hard to make friends. Any tips?",zh:"我很害羞，交朋友很难，有什么建议吗？",body:"Lunch and group work feel awkward. How did other new students start talking to people?",category:"Friends & Belonging",answers:7,time:"1d ago",badge:"Counselor Verified",answered:true},
  {id:"grade-drop",title:"What happens if my grade drops?",zh:"如果成绩下滑，我该怎么办？",body:"I’m worried about one class. When should I speak with my teacher or counselor?",category:"Classes & Grades",answers:6,time:"1d ago",badge:"Student Answer",answered:true},
  {id:"college",title:"How do I start college applications?",zh:"我该如何开始大学申请？",body:"What should I prepare first, and when should I meet the college and career counselor?",category:"College & Future",answers:8,time:"2d ago",badge:"Peer Mentor",answered:true},
];
const starterReplies: Record<string,Reply[]> = {
  graduate:[{id:"g1",author:"Mia",role:"Student",text:"先看自己的 transcript 和已获得的 credits，然后预约 counselor 一起核对毕业要求。",time:"1h ago"},{id:"g2",author:"Peer Mentor",role:"同伴导师",text:"You can also bring a list of the classes you are taking now. The counselor can help you make a semester-by-semester plan.",time:"45m ago"},{id:"g3",author:"Counselor",role:"辅导员确认",text:"Official graduation progress should always be confirmed with your assigned counselor.",time:"20m ago"}],
  english:[{id:"e1",author:"Lina",role:"Student",text:"我先从社团和同桌的一对一聊天开始，比在全班发言压力小很多。",time:"4h ago"},{id:"e2",author:"Peer Mentor",role:"同伴导师",text:"Try one small goal each day: ask one question, greet one classmate, or practice a sentence before class.",time:"3h ago"}],
  clubs:[{id:"c1",author:"Kai",role:"Student",text:"The activities office and the club directory are good places to start. Club Fair is especially helpful.",time:"Yesterday"},{id:"c2",author:"Yuki",role:"Student",text:"可以先选一个真正感兴趣的社团，第一次带朋友一起去也可以。",time:"Yesterday"}],
  friends:[{id:"f1",author:"Anonymous Student",role:"Student",text:"I started by sitting near the same people at lunch and saying hi every day. It became easier slowly.",time:"22h ago"},{id:"f2",author:"Counselor",role:"辅导员确认",text:"如果孤独感持续影响上学或睡眠，请来 counselor office，我们可以一起找支持。",time:"18h ago"}],
  "grade-drop":[{id:"d1",author:"Noah",role:"Student",text:"先看老师在成绩系统里的 comments，再把不懂的作业和问题写下来，office hours 会更有效率。",time:"20h ago"},{id:"d2",author:"Peer Mentor",role:"同伴导师",text:"One low grade does not define you. Ask early about corrections, tutoring, and a realistic catch-up plan.",time:"17h ago"},{id:"d3",author:"Counselor",role:"辅导员确认",text:"If several classes are becoming difficult at once, make an appointment so we can review workload and support options together.",time:"12h ago"}],
  college:[{id:"p1",author:"Avery",role:"Senior Student",text:"I started with a college list, activity record, and deadlines spreadsheet before writing essays.",time:"2d ago"},{id:"p2",author:"College & Career Counselor",role:"升学指导",text:"请先预约一次规划会谈。我们会根据年级、目标和家庭情况制定适合你的申请时间线。",time:"1d ago"}],
};
const categories=["Classes & Grades","Friends & Belonging","English & Communication","School Life","College & Future","Other"];
const initialFeed: FeedMessage[] = [
  {id:"m1",author:"Anonymous Student",role:"New question · 新问题",text:"I’m still learning how credits and graduation requirements work. Who should I ask to review my progress?",time:"2:20 PM",category:"Classes & Grades"},
  {id:"m2",author:"Mia",role:"Student",text:"先看自己的 transcript 和已获得的 credits，然后预约 counselor 一起核对毕业要求。",time:"2:23 PM",category:"Classes & Grades",replyTo:"回复 Anonymous Student"},
  {id:"m3",author:"Peer Mentor",role:"同伴导师",text:"Bring your current class list too. A counselor can help make a semester-by-semester plan.",time:"2:25 PM",category:"Classes & Grades",replyTo:"回复毕业进度问题"},
  {id:"m4",author:"Lina",role:"New question · 新问题",text:"我很想练习英语口语，但在全班面前说话会紧张。大家是怎么开始的？",time:"2:31 PM",category:"English & Communication"},
  {id:"m5",author:"Kai",role:"Student",text:"我从一对一聊天和参加社团开始，每天只给自己一个很小的目标。",time:"2:34 PM",category:"English & Communication",replyTo:"回复 Lina"},
  {id:"m6",author:"Anonymous Student",role:"New question · 新问题",text:"Does anyone know a club that is friendly to students who just arrived?",time:"2:40 PM",category:"School Life"},
  {id:"m7",author:"Yuki",role:"Student",text:"Club Fair 很适合先逛一圈。你也可以告诉我喜欢什么，我帮你一起找。",time:"2:42 PM",category:"School Life",replyTo:"回复社团问题"},
  {id:"m8",author:"Counselor",role:"辅导员",text:"提醒大家：正式的毕业要求和课程安排，请最后向 assigned counselor 确认。",time:"2:46 PM",category:"Classes & Grades"},
];
const feedTranslations: Record<string,string> = {
  m1:"我还在了解学分和毕业要求。应该请谁帮我检查毕业进度？", m2:"Check your transcript and earned credits first, then make an appointment with your counselor.",
  m3:"也请带上你现在的课程清单。辅导员可以帮你制定逐学期计划。", m4:"I want to practice spoken English, but speaking in front of the class makes me nervous. How did everyone start?",
  m5:"I started with one-on-one conversations and clubs, giving myself one small goal every day.", m6:"有人知道哪些社团对刚到学校的学生比较友好吗？",
  m7:"Club Fair is a good place to look around. Tell me what you like and I can help you search.", m8:"Reminder: confirm official graduation requirements and schedules with your assigned counselor.",
};

export default function ForumExperience(){
  const router=useRouter();
  const [questions,setQuestions]=useState<Question[]>(seed); const [popularOpen,setPopularOpen]=useState<string|null>(null);
  const [feed,setFeed]=useState<FeedMessage[]>(initialFeed); const [replyDraft,setReplyDraft]=useState("");
  const [autoTranslate,setAutoTranslate]=useState(true);
  const [query,setQuery]=useState(""); const [category,setCategory]=useState("All");
  const [mode,setMode]=useState<"Anonymous"|"Nickname">("Anonymous"); const [text,setText]=useState(""); const [postCategory,setPostCategory]=useState(categories[0]); const [notice,setNotice]=useState("");
  // eslint-disable-next-line react-hooks/set-state-in-effect -- Hydrate the user's local-only forum drafts after mount.
  useEffect(()=>{try{const saved=localStorage.getItem("bridge-forward-forum");if(saved){const local=(JSON.parse(saved) as Question[]).filter(q=>q.title!=="Too short");setQuestions([...local,...seed]);setFeed([...local.reverse().map(q=>({id:`feed-${q.id}`,author:"You",role:"My question · 我的问题",text:q.body,time:q.time,category:q.category,mine:true})),...initialFeed])}}catch{}},[]);
  const visibleFeed=useMemo(()=>feed.filter(m=>(category==="All"||m.category===category)&&`${m.author} ${m.text} ${m.category}`.toLowerCase().includes(query.toLowerCase())),[feed,query,category]);
  function publish(e:FormEvent){e.preventDefault();const clean=text.trim();if(clean.length<12){setNotice("请至少写 12 个字，让大家更容易理解你的问题。 / Please add a little more detail.");return;}const item:Question={id:`local-${Date.now()}`,title:clean.length>64?`${clean.slice(0,64)}…`:clean,zh:"我发布的问题",body:clean,category:postCategory,answers:0,time:"Just now",badge:mode==="Anonymous"?"Anonymous Student":"Community Nickname",answered:false,mine:true};const local=[item,...questions.filter(q=>q.id.startsWith("local-")&&q.title!=="Too short")];localStorage.setItem("bridge-forward-forum",JSON.stringify(local));setQuestions([item,...questions.filter(q=>q.title!=="Too short")]);setFeed(f=>[...f,{id:`feed-${item.id}`,author:"You",role:"My question · 我的问题",text:clean,time:"Just now",category:postCategory,mine:true}]);setText("");setNotice("发布成功！你的问题已出现在聊天广场。 / Your question is now visible in the campus chat.");}
  function sendReply(e:FormEvent){e.preventDefault();const clean=replyDraft.trim();if(!clean)return;setFeed(f=>[...f,{id:`message-${Date.now()}`,author:"You",role:mode==="Anonymous"?"Anonymous reply · 匿名回复":"Nickname reply · 昵称回复",text:clean,time:"Just now",category:"Other",mine:true}]);setReplyDraft("");}
  return <main className="peer-forum-page"><div className="peer-forum-shell">
    <button className="peer-forum-back" type="button" onClick={()=>window.history.length>1?router.back():router.push("/")}>← <span>Back · 返回上一页</span></button>
    <header className="peer-forum-hero"><div><h1>Ask &amp; Connect <em>♥</em></h1><p>Got questions? You’re not alone.<br/>Ask, share, and learn from each other.</p><p>有问题很正常，这里可以匿名提问，<br/>也可以阅读他人的经验与建议。</p></div><img src="/images/forum-students-hero-hd.png" alt="Students talking together on campus"/></header>
    <div className="peer-forum-grid"><div className="peer-forum-left">
      <section className="forum-glass-card forum-compose"><h2>Ask Your Question <span>提出问题</span></h2><small>Your question is important. We’re here to help.</small><div className="forum-mode" role="group" aria-label="Posting identity"><button className={mode==="Anonymous"?"active":""} onClick={()=>setMode("Anonymous")} type="button">Ask Anonymously 匿名提问</button><button className={mode==="Nickname"?"active":""} onClick={()=>setMode("Nickname")} type="button">Post with a Nickname 使用昵称</button></div><form onSubmit={publish}><textarea maxLength={500} onChange={e=>setText(e.target.value)} placeholder="What’s on your mind?  你想问什么？" value={text}/><span className="forum-count">{text.length}/500</span><div className="forum-category-picker">{categories.map(c=><button className={postCategory===c?"active":""} onClick={()=>setPostCategory(c)} type="button" key={c}>{c}</button>)}</div><button className="forum-post" type="submit">Post Question　发布问题　➤</button>{notice&&<p className="forum-notice" role="status">{notice}</p>}</form><p className="forum-respect">All questions should protect privacy and remain respectful.<br/>请勿填写真实姓名、电话、课表或其他私人信息。</p></section>
      <section className="forum-glass-card popular-topics"><h2>Popular Topics <span>热门话题</span></h2>{seed.slice(0,5).map((q,i)=><div className={`popular-topic-item ${popularOpen===q.id?"open":""}`} key={q.id}><button onClick={()=>setPopularOpen(popularOpen===q.id?null:q.id)} type="button"><b>{i+1}</b><span>{q.title}<small>{q.zh}</small></span><em>{popularOpen===q.id?"收起":"查看解答"}</em></button>{popularOpen===q.id&&<div className="popular-topic-answer"><p className="popular-question">{q.body}</p>{(starterReplies[q.id]??[]).map(reply=><article key={reply.id}><strong>{reply.author}<small>{reply.role}</small></strong><p>{reply.text}</p><time>{reply.time}</time></article>)}</div>}</div>)}</section>
    </div>
    <section className="forum-glass-card forum-browser"><div className="forum-chat-title"><div><span className="forum-online-dot"/>Campus Community Chat <small>校园聊天广场</small></div><button className={autoTranslate?"active":""} onClick={()=>setAutoTranslate(v=>!v)} type="button">Auto Translate <span>自动翻译</span> {autoTranslate?"ON":"OFF"}</button></div><p className="forum-chat-subtitle">Everyone can see questions and replies · 所有人都能看到提问与回复</p><div className="forum-search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search chat history… 搜索聊天记录…"/><select value={category} onChange={e=>setCategory(e.target.value)} aria-label="Filter category"><option>All</option>{categories.map(c=><option key={c}>{c}</option>)}</select></div>
      <div className="forum-group-chat"><div className="forum-group-messages">{visibleFeed.map(message=><article className={message.mine?"mine":""} key={message.id}><div className="forum-chat-avatar" aria-hidden="true">{message.author.slice(0,1)}</div><div className="forum-chat-message"><header><strong>{message.author}</strong><span>{message.role}</span><time>{message.time}</time></header>{message.replyTo&&<small>{message.replyTo}</small>}<p>{message.text}</p>{autoTranslate&&feedTranslations[message.id]&&<p className="forum-translation"><b>译</b>{feedTranslations[message.id]}</p>}<em>{message.category}</em></div></article>)}{!visibleFeed.length&&<div className="forum-no-replies">No matching chat messages.<br/>没有找到相关聊天记录。</div>}</div><form className="forum-reply-box forum-group-compose" onSubmit={sendReply}><textarea value={replyDraft} onChange={e=>setReplyDraft(e.target.value)} placeholder="Message the campus square… 在聊天广场发言…" rows={2}/><button type="submit">Send 发送</button></form></div>
    </section></div>
    <footer className="peer-forum-help forum-footer-natural"><div className="forum-footer-copy"><strong>Still need help? <span>还需要更多帮助？</span></strong><Link href="/school-information/people">Talk to a Peer Mentor<br/><span>联系同伴导师</span></Link><Link href="/school-information/people">Contact a Counselor<br/><span>联系辅导员</span></Link><Link href="/school-information/clubs">Visit the Activities Office<br/><span>访问活动办公室</span></Link></div></footer>
  </div></main>;
}
